---

- name: include os specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
  tags:
    - 'role::icinga2_agent'
    - 'role::icinga2_agent:install'

- import_tasks: installation.yml
  tags:
    - 'role::icinga2_agent'
    - 'role::icinga2_agent:install'
